apiVersion: v1
kind: Service
metadata:
  name: kubedoom
  namespace: {{ .Values.kubedoom.namespace | quote }}
  labels:
    app: kubedoom
spec:
  type: NodePort
  selector:
    app: kubedoom
  ports:
    - name: vnc 
      port: 5900
      targetPort: 5900
      nodePort: {{ .Values.kubedoom.vncNodePort }}