apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubedoom
  name: kubedoom
  namespace: {{ .Values.kubedoom.namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - image: ghcr.io/storax/kubedoom:latest
          env:
            - name: NAMESPACE
              value: {{ .Values.victims.namespace | quote }}
          name: kubedoom
          ports:
            - containerPort: 5900
              name: vnc