apiVersion: v1
kind: Service
metadata:
  name: app-2048
  namespace: {{ .Values.victims.namespace | quote }}
  labels:
    app: app-2048
spec:
  type: NodePort
  selector:
    app: app-2048
  ports:
    - port: 80
      targetPort: 80
      name: http
      nodePort: {{ .Values.victims.srvNodePort }}
